name: 'Corporate Numbers'
description: '国税庁法人番号'
inputs:
  destination:
    description: 'データ出力先ディレクトリ'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/bqfun/corporate_numbers:latest'
  env:
    DESTINATION: ${{ inputs.destination }}
