name: 'Accredited Foreign Manufacturers'
description: '外国製造業者認定・登録番号'
inputs:
  destination:
    description: 'データ出力先ディレクトリ'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/bqfun/accredited_foreign_manufacturers:latest'
  env:
    DESTINATION: ${{ inputs.destination }}
