on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.7
      - run: pip install black==20.8b1 isort==5.7.0
      - name: Lint with black and isort
        run: |
          black --check -l 79 .
          isort -c -m 3 --tc .
