on:
  push:
    branches:
      - main
    paths:
      - 'local_governments/**'
      - '.github/workflows/local_governments.yml'
  schedule:
      - cron: '0 0 * * *'

jobs:
  push_and_load:
    runs-on: ubuntu-latest
    if: github.repository == 'bqfun/jpdata'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./local_governments
          push: true
          tags: ghcr.io/bqfun/local_governments
      - uses: ./local_governments
        with:
          destination: /home/runner/work/jpdata/jpdata/outputs
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: bq load --replace --source_format=CSV --skip_leading_rows=1 local_governments.designated_cities outputs/designated_cities.csv local_governments/designated_cities_schema.json
      - run: bq load --replace --source_format=CSV --skip_leading_rows=1 local_governments.local_governments outputs/local_governments.csv local_governments/local_governments_schema.json
      - run: bq load --replace --source_format=CSV --allow_quoted_newlines --skip_leading_rows=1 local_governments.unions outputs/unions.csv local_governments/unions_schema.json
      - name: Instal IBM Cloud CLI
        run: curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
      - run: ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r ""
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      - run: ibmcloud cos put-object --bucket jpdata --region ap-geo --key local_governments/designated_cities.csv --body outputs/designated_cities.csv
      - run: ibmcloud cos put-object --bucket jpdata --region ap-geo --key local_governments/local_governments.csv --body outputs/local_governments.csv
      - run: ibmcloud cos put-object --bucket jpdata --region ap-geo --key local_governments/unions.csv --body outputs/unions.csv
