on:
  push:
    branches:
      - main
    paths:
      - 'local_governments/**'
      - '.github/workflows/local_governments.yml'
  schedule:
      - cron: '0 0 * * *'

defaults:
  run:
    working-directory: local_governments

jobs:
  push_and_load:
    runs-on: ubuntu-latest
    if: github.repository == 'bqfun/jpdata'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./local_governments
          push: true
          tags: ghcr.io/bqfun/local_governments
      - uses: ./local_governments
        with:
          destination: /home/runner/work/jpdata/jpdata/local_governments/outputs
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -r outputs gs://bqfun-jpdata/local_governments
      - run: bq load --source_format=CSV --skip_leading_rows=1 local_governments.designated_cities outputs/designated_cities.csv outputs/designated_cities_schema.json
      - run: bq load --source_format=CSV --skip_leading_rows=1 local_governments.local_governments outputs/local_governments.csv outputs/local_governments_schema.json
      - run: bq load --source_format=CSV --skip_leading_rows=1 local_governments.unions outputs/unions.csv outputs/unions_schema.json
