on:
  push:
    branches:
      - main
    paths:
      - 'national_holidays/**'
      - '.github/workflows/national_holidays.yml'
  schedule:
      - cron: '0 0 * * 0'

defaults:
  run:
    working-directory: national_holidays

jobs:
  push_and_load:
    runs-on: ubuntu-latest
    if: github.repository == 'bqfun/jpdata'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./national_holidays
          push: true
          tags: ghcr.io/bqfun/national_holidays
      - uses: ./national_holidays
        with:
          destination: /home/runner/work/jpdata/jpdata/national_holidays/outputs
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -r outputs gs://bqfun-jpdata/national_holidays
      - run: bq load --source_format=CSV --skip_leading_rows=1 national_holidays.national_holidays national_holidays.csv national_holidays_schema.json
