on:
  push:
    branches:
      - main
    paths:
      - 'national_holidays/**'
      - '.github/workflows/national_holidays.yml'
  schedule:
      - cron: '0 0 * * *'

jobs:
  push_and_load:
    runs-on: ubuntu-latest
    if: github.repository == 'bqfun/jpdata'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./national_holidays
          push: true
          tags: ghcr.io/bqfun/national_holidays
      - uses: ./national_holidays
        with:
          destination: /home/runner/work/jpdata/jpdata/outputs
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: bq load --source_format=CSV --skip_leading_rows=1 national_holidays.national_holidays outputs/national_holidays.csv national_holidays/national_holidays_schema.json
      - name: Instal IBM Cloud CLI
        run: curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
      - run: ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r ""
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      - run: ibmcloud cos put-object --bucket jpdata --region ap-geo --key national_holidays/national_holidays.csv --body outputs/national_holidays.csv
