on:
  push:
    branches:
      - main
    paths:
      - 'number_of_births/**'
      - '.github/workflows/number_of_births.yml'
  schedule:
      - cron: '0 0 * * 0'

jobs:
  push_and_load:
    runs-on: ubuntu-latest
    if: github.repository == 'bqfun/jpdata'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build \
                  -Dimage=ghcr.io/bqfun/number_of_births
        working-directory: number_of_births
      - uses: ./number_of_births
        with:
          destination: /home/runner/work/jpdata/jpdata/outputs
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: bq load --replace --source_format=CSV --skip_leading_rows=1 number_of_births.number_of_births outputs/number_of_births.csv number_of_births/number_of_births_schema.json
      - name: Instal IBM Cloud CLI
        run: curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
      - run: ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r ""
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      - run: ibmcloud cos put-object --bucket jpdata --region ap-geo --key number_of_births/number_of_births.csv --body outputs/number_of_births.csv
